import { StyleSheet } from "@react-pdf/renderer";

export const colors = {
  midnight: "#0F1B2D",
  deepNavy: "#162A45",
  slate: "#1E3A5F",
  teal: "#1A7A6D",
  tealLight: "#2BA89A",
  tealPale: "#D0F0EC",
  tealMuted: "#B8E6DF",
  ocean: "#1B6B93",
  oceanLight: "#4A9CC7",
  oceanPale: "#D6EDF7",
  ice: "#E8F4F8",
  iceDeep: "#D1E9F2",
  warmOrange: "#E8943A",
  warmOrangePale: "#FFF3E0",
  coral: "#E07C5A",
  softGreen: "#4CAF7D",
  softGreenPale: "#E8F5E9",
  softGreenMuted: "#C8E6D0",
  lavender: "#7E6BA1",
  lavenderPale: "#F0EAF5",
  gold: "#D4A843",
  goldPale: "#FFF8E1",
  textDark: "#1A1A2E",
  textMid: "#4A4A6A",
  textLight: "#8A8AA0",
  white: "#FFFFFF",
  offWhite: "#F8FAFB",
  lightGray: "#E8ECF0",
  mediumGray: "#C0C8D0",
  sampleBlue: "#E3F2FD",
  sampleText: "#5C8BC7",
  sampleCheck: "#2BA89A",
};

export const pageWidth = 612;
export const pageHeight = 792;
export const margin = 36;

export const sharedStyles = StyleSheet.create({
  page: {
    padding: margin,
    fontFamily: "Helvetica",
    fontSize: 10,
    color: colors.textDark,
    backgroundColor: colors.white,
  },
  pageHeader: {
    marginBottom: 14,
    paddingBottom: 10,
    borderBottomWidth: 2,
    borderBottomColor: colors.tealPale,
  },
  pageTitle: {
    fontSize: 20,
    fontFamily: "Helvetica-Bold",
    color: colors.deepNavy,
    marginBottom: 3,
  },
  pageSubtitle: {
    fontSize: 10,
    color: colors.textMid,
    fontFamily: "Helvetica",
    lineHeight: 1.4,
  },
  sectionTitle: {
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    color: colors.teal,
    marginBottom: 6,
    marginTop: 8,
  },
  smallLabel: {
    fontSize: 7,
    fontFamily: "Helvetica-Bold",
    color: colors.textMid,
    textTransform: "uppercase" as const,
    letterSpacing: 0.6,
  },
  line: {
    borderBottomWidth: 0.5,
    borderBottomColor: colors.lightGray,
    marginTop: 3,
    marginBottom: 3,
  },
  lineSpacious: {
    borderBottomWidth: 0.75,
    borderBottomColor: colors.lightGray,
    marginTop: 4,
    marginBottom: 4,
  },
  checkbox: {
    width: 11,
    height: 11,
    borderWidth: 1,
    borderColor: colors.tealMuted,
    borderRadius: 2,
    marginRight: 6,
    flexShrink: 0,
  },
  checkboxChecked: {
    width: 11,
    height: 11,
    borderWidth: 1,
    borderColor: colors.teal,
    backgroundColor: colors.tealPale,
    borderRadius: 2,
    marginRight: 6,
    flexShrink: 0,
    justifyContent: "center" as const,
    alignItems: "center" as const,
  },
  row: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
  },
  footer: {
    position: "absolute" as const,
    bottom: 22,
    left: margin,
    right: margin,
    flexDirection: "row" as const,
    justifyContent: "space-between" as const,
    alignItems: "center" as const,
    paddingTop: 8,
    borderTopWidth: 0.5,
    borderTopColor: colors.lightGray,
  },
  footerText: {
    fontSize: 7,
    color: colors.textLight,
    fontFamily: "Helvetica",
  },
  headerBadge: {
    fontSize: 7,
    fontFamily: "Helvetica-Bold",
    color: colors.white,
    backgroundColor: colors.teal,
    paddingTop: 3,
    paddingBottom: 3,
    paddingLeft: 10,
    paddingRight: 10,
    borderRadius: 10,
    textTransform: "uppercase" as const,
    letterSpacing: 1,
    alignSelf: "flex-start" as const,
  },
  card: {
    backgroundColor: colors.offWhite,
    borderRadius: 4,
    paddingTop: 8,
    paddingBottom: 8,
    paddingLeft: 10,
    paddingRight: 10,
    marginBottom: 8,
    borderWidth: 0.5,
    borderColor: colors.lightGray,
  },
  cardTeal: {
    backgroundColor: colors.tealPale,
    borderRadius: 4,
    paddingTop: 8,
    paddingBottom: 8,
    paddingLeft: 10,
    paddingRight: 10,
    marginBottom: 8,
    borderLeftWidth: 3,
    borderLeftColor: colors.teal,
  },
  inputField: {
    height: 22,
    borderBottomWidth: 0.75,
    borderBottomColor: colors.mediumGray,
    paddingBottom: 2,
    justifyContent: "flex-end" as const,
  },
  tableHeader: {
    flexDirection: "row" as const,
    backgroundColor: colors.deepNavy,
    paddingTop: 6,
    paddingBottom: 6,
    paddingLeft: 8,
    paddingRight: 8,
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
  },
  tableHeaderText: {
    fontSize: 7,
    fontFamily: "Helvetica-Bold",
    color: colors.tealLight,
    textTransform: "uppercase" as const,
    letterSpacing: 0.5,
  },
  tableRow: {
    flexDirection: "row" as const,
    paddingTop: 5,
    paddingBottom: 5,
    paddingLeft: 8,
    paddingRight: 8,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.lightGray,
    alignItems: "center" as const,
  },
  tableRowAlt: {
    flexDirection: "row" as const,
    paddingTop: 5,
    paddingBottom: 5,
    paddingLeft: 8,
    paddingRight: 8,
    backgroundColor: colors.offWhite,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.lightGray,
    alignItems: "center" as const,
  },
  sampleBox: {
    backgroundColor: colors.sampleBlue,
    borderRadius: 3,
    paddingTop: 3,
    paddingBottom: 3,
    paddingLeft: 5,
    paddingRight: 5,
    borderWidth: 0.5,
    borderColor: "#B8D4E8",
  },
  sampleText: {
    fontSize: 7,
    color: colors.sampleText,
    fontFamily: "Helvetica-Oblique",
  },
});
