import { StyleSheet } from "@react-pdf/renderer";

export const colors = {
  midnight: "#0F1B2D",
  deepNavy: "#162A45",
  slate: "#1E3A5F",
  teal: "#1A7A6D",
  tealLight: "#2BA89A",
  tealPale: "#D0F0EC",
  tealMuted: "#B8E6DF",
  ocean: "#1B6B93",
  oceanLight: "#4A9CC7",
  ice: "#E8F4F8",
  warmOrange: "#E8943A",
  warmOrangePale: "#FFF3E0",
  coral: "#E07C5A",
  softGreen: "#4CAF7D",
  softGreenPale: "#E8F5E9",
  softGreenMuted: "#C8E6D0",
  lavender: "#7E6BA1",
  lavenderPale: "#F0EAF5",
  gold: "#D4A843",
  goldPale: "#FFF8E1",
  textDark: "#1A1A2E",
  textMid: "#4A4A6A",
  textLight: "#8A8AA0",
  white: "#FFFFFF",
  offWhite: "#F8FAFB",
  lightGray: "#E8ECF0",
  mediumGray: "#C0C8D0",
  sampleBlue: "#E3F2FD",
  sampleText: "#5C8BC7",
};

export const pageWidth = 612;
export const pageHeight = 792;
export const margin = 32;

export const sharedStyles = StyleSheet.create({
  page: {
    padding: margin,
    fontFamily: "Helvetica",
    fontSize: 9,
    color: colors.textDark,
    backgroundColor: colors.white,
  },
  pageHeader: {
    marginBottom: 10,
    paddingBottom: 8,
    borderBottomWidth: 1.5,
    borderBottomColor: colors.tealPale,
  },
  pageTitle: {
    fontSize: 18,
    fontFamily: "Helvetica-Bold",
    color: colors.deepNavy,
    marginBottom: 2,
  },
  pageSubtitle: {
    fontSize: 9,
    color: colors.textMid,
    lineHeight: 1.3,
  },
  sectionTitle: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: colors.teal,
    marginBottom: 4,
    marginTop: 6,
  },
  smallLabel: {
    fontSize: 6,
    fontFamily: "Helvetica-Bold",
    color: colors.textMid,
    textTransform: "uppercase" as const,
    letterSpacing: 0.5,
  },
  line: {
    borderBottomWidth: 0.5,
    borderBottomColor: colors.lightGray,
    marginTop: 2,
    marginBottom: 2,
  },
  lineSpacious: {
    borderBottomWidth: 0.5,
    borderBottomColor: colors.lightGray,
    marginTop: 3,
    marginBottom: 3,
  },
  checkbox: {
    width: 9,
    height: 9,
    borderWidth: 0.75,
    borderColor: colors.tealMuted,
    borderRadius: 1.5,
    marginRight: 4,
    flexShrink: 0,
  },
  row: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
  },
  footer: {
    flexDirection: "row" as const,
    justifyContent: "space-between" as const,
    alignItems: "center" as const,
    marginTop: "auto" as const,
    paddingTop: 6,
    borderTopWidth: 0.5,
    borderTopColor: colors.lightGray,
  },
  footerText: {
    fontSize: 6,
    color: colors.textLight,
    fontFamily: "Helvetica",
  },
  headerBadge: {
    fontSize: 6,
    fontFamily: "Helvetica-Bold",
    color: colors.white,
    backgroundColor: colors.teal,
    paddingTop: 2,
    paddingBottom: 2,
    paddingLeft: 8,
    paddingRight: 8,
    borderRadius: 8,
    textTransform: "uppercase" as const,
    letterSpacing: 0.8,
    alignSelf: "flex-start" as const,
  },
  tableHeader: {
    flexDirection: "row" as const,
    backgroundColor: colors.deepNavy,
    paddingTop: 4,
    paddingBottom: 4,
    paddingLeft: 6,
    paddingRight: 6,
    borderTopLeftRadius: 3,
    borderTopRightRadius: 3,
  },
  tableHeaderText: {
    fontSize: 6,
    fontFamily: "Helvetica-Bold",
    color: colors.tealLight,
    textTransform: "uppercase" as const,
    letterSpacing: 0.4,
  },
  tableRow: {
    flexDirection: "row" as const,
    paddingTop: 3,
    paddingBottom: 3,
    paddingLeft: 6,
    paddingRight: 6,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.lightGray,
    alignItems: "center" as const,
  },
  tableRowAlt: {
    flexDirection: "row" as const,
    paddingTop: 3,
    paddingBottom: 3,
    paddingLeft: 6,
    paddingRight: 6,
    backgroundColor: colors.offWhite,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.lightGray,
    alignItems: "center" as const,
  },
  sampleBox: {
    backgroundColor: colors.sampleBlue,
    borderRadius: 2,
    paddingTop: 2,
    paddingBottom: 2,
    paddingLeft: 4,
    paddingRight: 4,
    borderWidth: 0.5,
    borderColor: "#B8D4E8",
  },
  sampleText: {
    fontSize: 6,
    color: colors.sampleText,
    fontFamily: "Helvetica-Oblique",
  },
});
